baseurl: "/"
languageCode: "en-us"
title: "Microeconomic data analysis"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Material 
      url: "material/"
      weight: 2
    - name: Tutorials
      url: "tutorials/"
      weight: 3
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "Course material for 'Microeconomic data analysis'."
  footer: "&copy; [Claudius Gräbner-Radkowitsch](https://claudius-graebner.com/) 2021 -- 2022 | [Github](https://github.com/graebnerc) | [Twitter](https://twitter.com/ClaudiusGrabner)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
